sudo: required
dist: xenial
services:
- docker
env:
  global:
  - PKGFORGE_STATEFILE=/tmp/pkgforge
  - secure: Dseu8hy7lOQkAuU651uRwIFUcYeGq1cXtOj0bhDgpUhKY3hP0QzbBZj1uZKyhzISwN0b5pO2cMjVZi/TZDAl4oh+BFG3nMBfhqerVz5WiXyk1mPJuwLuXmcEQS060S8C7RGTefB0LqNa2YIhoABsTgpu8/LMs+iDXt4TvO1wWI4iB8g73TjhZIVl9+0MlP6CY7xc6uzoPNanPaWBSaUaZoTbCMhOSyu6lxFVfuKP+IGUOjDolahE9yMNwhbfBUQMwdUh8/VOiCTpMIvTWeElZh1W2xq33NRLNbQZZ5QoFwI3Pzvdp3FKiqmW1YAAkuUq1IxwUrwQk6Ar5EcKG6QeR2+uXXcqEafs44jMDcIJb6A1vn7LUrxebfOjuhhnl7zwyjTOBefl5+fz8LK8PZ9wq21kWedJ8veEp1cOPfMFRebmYyy3bnn9p9YVTYF3bE8tkldKGNP6rD+KsPaMeLwy2qyta2L0anhaNStb2JpQ6O674CGBz35AOMoMoG3B2rYvjH56SDqpiycPRuvI+Naj91OQsV5oyqNOohdZ1TcqM4FP0JeFPH81jUAsMWUeyUbje5UDFaXfa+q1Dm0V3f7S3ERFpmCh7pGPzimvnsI9zoq9AfxdrOykyVVwqv/JMUE0Qi3Es95bbm3rvNimgZCdLdjx+x3q6a9W0iUyHSBGXpU=
script: make
deploy:
  provider: script
  script: make release || travis_terminate 1
  skip_cleanup: true
  on:
    tags: true
notifications:
  email: false
  slack:
    secure: hrvSpL2+9H9evllsRLbLav/nzQp5j5G8kaaHT4BmWQdGcAn6EEada0ZbKpN+jbfloGHC+7vHml59XNRCTUw00ptlgkwe5aX7pKHDU9TlG4KpufSSXzugYqfgE1y0KwMVRYvRZBIXgyOP3pE16us2bKL7qur4YpO7IwBuDoU9wFuz1BoZqxfo42Et8gyiEucHjCVoH1H2v5v7Htw37UfkMfzcQYQfQe8gFR8fZ8oI/W/1uTTTX6KVQGbXW0tJPwCoHlVJ+P6qsekw4v9HvrxxG2FcYkq6W8ccU8/eZg3Ay7H2YEOErBuOUGwxO8+Cpf1vU9apY9kxVswxFnvI1Fi8VtFWGl6AvrPr5hiaA9PriV9dnfjtv/KENyofn4JAOCcROcZ58avo39I1wIDk8InWlJbLizNl8Fd9tAxfctF3DFj4SV9NukBhys1ZeGGjF8iZMhlQNkejgWYzA8jtlygWgVl8BZl+yQ0qtTxg52QGFfAAxNoouq94Qdjnf4tDmNLsgmBXo3G7pYWY+xgJOnzIjInlMiU6CzOVCnGDzw+WNzZZx+SfDeCy9ws+mCHC1EL5IB0f9EfyGLFmUmOPzaAZtvsHJcH36IWtgcL+A7A9rowOXbSJ5ZFr1RYswARxlMq9yPsUDT34EdrWAPnYZ8yBzbMWkt16kCKLVdK7UD83sLk=
